### ISSUE TITLE
tooltips on stocks list contain empty titles

### ISSUE THREAD

**Issue by dimbleby** [will-normand/drinc-prediction-contest#1]
Like this:

```
<a href="https://www.google.co.uk/finance?q=LON:ADM" rel="tooltip" data-placement="right" title="">
```

I believe I used to maintain the stocks dictionary in PredictionContest.py (which was a bit crap) and it looks as though you've moved this data to the database (which makes sense).  But you seem to have lost the full name of the stock so that these tooltips no longer work.

(Also while you're there: the internet suggests that the current fashion is for `data-toggle="tooltip"` rather than `rel="tooltip"`).

**Comment by will-normand** [comment]
The name of the stock is available in PredictionContest.py, so it should be easy to expose in the web page. 

The implementation of loading the stocks isn't great - it breaks the app if you delete a stock, so it would be nice to improve that at the same time.

**Comment by will-normand** [comment]
All the plumbing for stock names was actually there already - it's just that nothing was adding them to the database.  I've added names manually for now.
